// <auto-generated />
namespace SmartRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class modelnazivfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelnazivfix));
        
        string IMigrationMetadata.Id
        {
            get { return "202605021258180_model-naziv-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
